' ******************************************************************************
' swxJRNL.swj - journal recorded on 04/28/24 by Wardhana Raihandika
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "PROTO ASSEMBLY FINAL", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.07244521858570915351, 0.1820695742421361563, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.07244521858570915351, 0.1820695742421361563, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02897808743428366418, 0.06425984973251863686, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, 0.04283989982167910049, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01931872495618910945, 0.05354987477709886173, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03380776867333094154, 0.08567979964335820098, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01448904371714183209, 0.06425984973251863686, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01931872495618910945, 0.06425984973251863686, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02897808743428366418, 0.1178097245096175055, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03863744991237821891, 0.1285196994650372737, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.053126493629520051, 0.171359599286716402, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.08693426230285099254, 0.224909474063815229, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.08210458106380370824, 0.1820695742421361563, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.08693426230285099254, 0.1499396493758768378, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.053126493629520051, 0.07496982468793841892, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02414840619523638682, 0.01070997495541977512, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01448904371714183209, -0.02141994991083955024, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01448904371714183209, -0.1927795491975559106, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04829681239047277364, -0.5569186976818282231, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1304013934542764819, -0.6318885223697666698, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1400607559323710505, -0.4069790483059513853, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1207420309761819271, -0.1499396493758768378, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1159123497371346567, -0.06425984973251863686, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.106252987259040102, 0.01070997495541977512, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07244521858570915351, 0.2463294239746547931, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02897808743428366418, 0.2998792987517536757, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.07244521858570915351, 0.5462087227264084133, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06761553734666188309, 0.2891693237963339214, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04346713115142549627, 0.09638977459877795528, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06278585610761459879, 0.1285196994650372737, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.07244521858570915351, 0.1392296744204570558, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02414840619523638682, 0.01070997495541977512, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01448904371714183209, -0.08567979964335820098, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.09638977459877795528, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06278585610761459879, -0.1606496243312966199, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07244521858570915351, -0.09638977459877795528, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.053126493629520051, -0.03212992486625931843, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.053126493629520051, 0, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03380776867333094154, 0, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02897808743428366418, 0.04283989982167910049, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.08210458106380370824, 0.03212992486625931843, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.009659362478094554727, 0.02141994991083955024, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07727489982475643782, -0.1820695742421361563, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.09659362478094554727, -0.4926588479493095862, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04346713115142549627, -0.1606496243312966199, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04346713115142549627, -0.06425984973251863686, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07244521858570915351, -0.06425984973251863686, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02414840619523638682, 0, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.009659362478094554727, 0, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01448904371714183209, 0.06425984973251863686, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0.09638977459877795528, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.1499396493758768378, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04346713115142549627, 0.224909474063815229, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05795617486856732836, 0.171359599286716402, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.053126493629520051, 0.1070997495541977235, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04829681239047277364, 0.06425984973251863686, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.053126493629520051, 0.05354987477709886173, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03863744991237821891, 0, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03863744991237821891, -0.03212992486625931843, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01448904371714183209, -0.04283989982167910049, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05354987477709886173, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02897808743428366418, -0.1070997495541977235, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.08693426230285099254, -0.1285196994650372737, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04346713115142549627, -0.01070997495541977512, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02414840619523638682, 0.02141994991083955024, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.009659362478094554727, 0.06425984973251863686, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0.08567979964335820098, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03863744991237821891, 0.1285196994650372737, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04346713115142549627, 0.07496982468793841892, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.053126493629520051, 0.03212992486625931843, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.053126493629520051, 0.03212992486625931843, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02897808743428366418, 0, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, 0, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03863744991237821891, 0, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04346713115142549627, 0, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03863744991237821891, 0, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0.03212992486625931843, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0.01070997495541977512, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, 0.04283989982167910049, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04346713115142549627, 0.01070997495541977512, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01931872495618910945, -0.1070997495541977235, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.1285196994650372737, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, -0.05354987477709886173, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01931872495618910945, -0.03212992486625931843, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03380776867333094154, -0.03212992486625931843, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02414840619523638682, 0, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.009659362478094554727, 0.01070997495541977512, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0.06425984973251863686, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01931872495618910945, 0.06425984973251863686, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03380776867333094154, 0.03212992486625931843, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01931872495618910945, 0.02141994991083955024, 0.0517578723274639621, 0.2464977608160536793, 0.1384473497555445409

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.08567979964335820098, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.03212992486625931843, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03212992486625931843, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04346713115142549627, 0, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01448904371714183209, 0.02141994991083955024, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06425984973251863686, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, 0.171359599286716402, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02414840619523638682, 0.09638977459877795528, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03863744991237821891, 0.05354987477709886173, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03380776867333094154, 0, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.05354987477709886173, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.02141994991083955024, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.03212992486625931843, 0.0612177012214374372, 0.1095598164414468556, 0.1912821471671009022

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.07385426686690266251, 0.1476290802354753851, 0.1981696759312967515, 0.3422288585458242438, 0.2061287517146277448, -0.9167280655107007403, 0.0003009849280259839304, 1, True, 0, 0)
boolstatus = Part.Extension.SelectByRay(0.0546803089868888037, 0.1447625304225539367, 0.1981415210542536443, 0.3422288585458242438, 0.2061287517146277448, -0.9167280655107007403, 0.0003009849280259839304, 1, True, 0, 0)
dblDimXPertTextPos(0) = 0.058968
dblDimXPertTextPos(1) = 0.147428
dblDimXPertTextPos(2) = 0.184584
varDimXPertTextPos = dblDimXPertTextPos
swDimXPertDimOpt.TextPosition = varDimXPertTextPos
boolstatus = swDimXPertPart.InsertLocationDimension(swDimXPertDimOpt)
Part.ClearSelection2 True
Part.SetPickMode
Part.ClearSelection2 True
Dim swConfig As Object
Dim swDimXPertMgr As Object
Dim swDimXPertPart As Object
Dim swDimXPertDimOpt As Object
Dim dblDimXPertTextPos() As Double
ReDim dblDimXPertTextPos(0 To 2) As Double
Dim varDimXPertTextPos As Variant
Set swConfig = Part.ConfigurationManager.ActiveConfiguration
Set swDimXPertMgr = Part.Extension.DimXpertManager(swConfig.Name, True)
Set swDimXPertPart = swDimXPertMgr.DimXpertPart
Set swDimXPertDimOpt = swDimXPertPart.GetDimOption
boolstatus = Part.Extension.SelectByRay(0.05107347449325061461, 0.1439413551477741748, 0.1982987321759424049, 0.3422288585458242438, 0.2061287517146277448, -0.9167280655107007403, 0.0002024216515439934184, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByRay(0.0417727515876435973, 0.1357818227069600425, 0.199384502167674782, 0.3422288585458242438, 0.2061287517146277448, -0.9167280655107007403, 0.0002024216515439934184, 2, True, 0, 0)
dblDimXPertTextPos(0) = 0.053611
dblDimXPertTextPos(1) = 0.121502
dblDimXPertTextPos(2) = 0.187050
varDimXPertTextPos = dblDimXPertTextPos
swDimXPertDimOpt.TextPosition = varDimXPertTextPos
boolstatus = swDimXPertPart.InsertLocationDimension(swDimXPertDimOpt)
Part.ClearSelection2 True
ReDim dblDimXPertTextPos(0 To 2) As Double
Set swConfig = Part.ConfigurationManager.ActiveConfiguration
Set swDimXPertMgr = Part.Extension.DimXpertManager(swConfig.Name, True)
Set swDimXPertPart = swDimXPertMgr.DimXpertPart
Set swDimXPertDimOpt = swDimXPertPart.GetDimOption
boolstatus = Part.Extension.SelectByRay(0.05892805852380433862, 0.1252687313962468352, 0.1769546690339325323, 0.3422288585458242438, 0.2061287517146277448, -0.9167280655107007403, 0.000239548441545357234, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.05892805852380433862, 0.1252687313962468352, 0.1769546690339325323, False, 0, Nothing, 0)
Part.ClearSelection2 True
Part.SetPickMode
Part.ClearSelection2 True
ReDim dblDimXPertTextPos(0 To 2) As Double
Set swConfig = Part.ConfigurationManager.ActiveConfiguration
Set swDimXPertMgr = Part.Extension.DimXpertManager(swConfig.Name, True)
Set swDimXPertPart = swDimXPertMgr.DimXpertPart
Set swDimXPertDimOpt = swDimXPertPart.GetDimOption
boolstatus = Part.Extension.SelectByRay(0.04290730731997882685, 0.1072972397583953352, 0.1990205250373833223, 0.3422288585458242438, 0.2061287517146277448, -0.9167280655107007403, 0.0003449497558253143844, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByRay(0.03172602904345467323, 0.1367236180300892556, 0.2027015589533220918, 0.3422288585458242438, 0.2061287517146277448, -0.9167280655107007403, 0.0003449497558253143844, 2, True, 0, 0)
dblDimXPertTextPos(0) = 0.038863
dblDimXPertTextPos(1) = 0.102134
dblDimXPertTextPos(2) = 0.207084
varDimXPertTextPos = dblDimXPertTextPos
swDimXPertDimOpt.TextPosition = varDimXPertTextPos
boolstatus = swDimXPertPart.InsertLocationDimension(swDimXPertDimOpt)
Part.ClearSelection2 True
Part.SetPickMode
Part.ClearSelection2 True
ReDim dblDimXPertTextPos(0 To 2) As Double
Set swConfig = Part.ConfigurationManager.ActiveConfiguration
Set swDimXPertMgr = Part.Extension.DimXpertManager(swConfig.Name, True)
Set swDimXPertPart = swDimXPertMgr.DimXpertPart
Set swDimXPertDimOpt = swDimXPertPart.GetDimOption
boolstatus = Part.Extension.SelectByRay(0.04197329153197415508, 0.1372493903175495689, 0.1993742052194988901, 0.3422288585458242438, 0.2061287517146277448, -0.9167280655107007403, 0.0003379288679384252129, 2, False, 0, 0)
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01070997495541977512, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02414840619523638682, -0.01070997495541977512, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03863744991237821891, 0, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03863744991237821891, 0, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01448904371714183209, 0.03212992486625931843, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, 0, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01448904371714183209, 0.03212992486625931843, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02414840619523638682, 0.03212992486625931843, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02414840619523638682, 0.03212992486625931843, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01931872495618910945, 0, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, -0.02141994991083955024, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.04283989982167910049, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.05354987477709886173, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.03212992486625931843, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, -0.05354987477709886173, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, -0.01070997495541977512, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01931872495618910945, -0.01070997495541977512, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02897808743428366418, -0.01070997495541977512, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02897808743428366418, -0.02141994991083955024, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03380776867333094154, -0.04283989982167910049, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02414840619523638682, -0.02141994991083955024, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06761553734666188309, -0.02141994991083955024, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01448904371714183209, 0, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01448904371714183209, 0, 0.05382471752025708156, 0.1451445318004971341, 0.1985244570224722338

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
ReDim dblDimXPertTextPos(0 To 2) As Double
Set swConfig = Part.ConfigurationManager.ActiveConfiguration
Set swDimXPertMgr = Part.Extension.DimXpertManager(swConfig.Name, True)
Set swDimXPertPart = swDimXPertMgr.DimXpertPart
Set swDimXPertDimOpt = swDimXPertPart.GetDimOption
boolstatus = Part.Extension.SelectByRay(0.05217912362690668715, 0.1443418420213982145, 0.1982713521990149275, -0.1221105295082386133, -0.00653821515694813938, -0.992494972443578316, 0.0001529407472403660016, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByRay(0.04188545643958008213, 0.1363318661700887446, 0.1993988468268526049, -0.1221105295082386133, -0.00653821515694813938, -0.992494972443578316, 0.0001529407472403660016, 2, True, 0, 0)
dblDimXPertTextPos(0) = 0.048517
dblDimXPertTextPos(1) = 0.134888
dblDimXPertTextPos(2) = 0.187544
varDimXPertTextPos = dblDimXPertTextPos
swDimXPertDimOpt.TextPosition = varDimXPertTextPos
boolstatus = swDimXPertPart.InsertLocationDimension(swDimXPertDimOpt)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, 0.06425984973251863686, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04283989982167910049, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02141994991083955024, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0.03212992486625931843, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0.02141994991083955024, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.009659362478094554727, 0, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02414840619523638682, -0.01070997495541977512, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.009659362478094554727, -0.04283989982167910049, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04283989982167910049, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05354987477709886173, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.04283989982167910049, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.04283989982167910049, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.07496982468793841892, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.05354987477709886173, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.04283989982167910049, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.04283989982167910049, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.07496982468793841892, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, -0.08567979964335820098, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.06425984973251863686, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04283989982167910049, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, -0.04283989982167910049, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, -0.05354987477709886173, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, -0.03212992486625931843, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.07496982468793841892, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.1927795491975559106, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, 0.1392296744204570558, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.1070997495541977235, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, 0.1070997495541977235, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.1392296744204570558, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.08567979964335820098, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03212992486625931843, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0.03212992486625931843, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01931872495618910945, 0, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03863744991237821891, 0, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, -0.01070997495541977512, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, -0.01070997495541977512, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01070997495541977512, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.06425984973251863686, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, -0.05354987477709886173, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02414840619523638682, -0.01070997495541977512, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, 0, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, 0, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, 0, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01070997495541977512, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02141994991083955024, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02141994991083955024, 0.04934783041777279777, 0.1446611364306833458, 0.1989266389107910982

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("TXD4@Scheme2", "DIMENSION", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(0.05067157925758891679, 0.1017988228495880776, 0.1974462653311093163, -0.1021724014761151017, 0.1330046751890080758, -0.9858349541147696238, 0.0005422075744898689331, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.05067157925758891679, 0.1017988228495880776, 0.1974462653311093163, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(0.08775364318294265331, 0.1632081589197298399, 0.1847751816186473661, -0.1021724014761151017, 0.1330046751890080758, -0.9858349541147696238, 0.0005422075744898689331, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.08775364318294265331, 0.1632081589197298399, 0.1847751816186473661, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Pinkie Rod-4@PROTO ASSEMBLY FINAL", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Dim TransformData() As Double
ReDim TransformData(0 To 15) As Double
TransformData(0) = 0.1163086918294174432
TransformData(1) = -0.01680045443693420348
TransformData(2) = 0.9930710110237042088
TransformData(3) = 0.9932106691247707397
TransformData(4) = -0.0002507456806653287056
TransformData(5) = -0.1163292906508455182
TransformData(6) = 0.00220339321386845647
TransformData(7) = 0.9998588309643098304
TransformData(8) = 0.01665722669080759583
TransformData(9) = 0.07779528266467279629
TransformData(10) = 0.1709974291652054668
TransformData(11) = 0.1820453739761221101
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
Dim TransformDataVariant As Variant
TransformDataVariant = TransformData
Dim swMathUtil As Object
Set swMathUtil = swApp.GetMathUtility()
Dim swTransform As Object
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Dim swComp As Object
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
boolstatus = Part.Extension.SelectByRay(0.05691027728397894669, 0.09576764998802013429, 0.1908290452367006063, -0.1021724014761151017, 0.1330046751890080758, -0.9858349541147696238, 0.0005422075744898689331, 3, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "VERTEX", 0.05691027728397894669, 0.09576764998802013429, 0.1908290452367006063, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.0633497801013831463, 0.09895209027504847654, 0.1962034614906542629, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.06072407205839169819, 0.0986002562018484241, 0.1949194731819261506, False, 0, Nothing, 0)
boolstatus = Part.ForceRebuild3(False)
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.06228638587582224773, 0.1011279334089181248, 0.1966652323481525855, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("", "VERTEX", 0.05683358736321725974, 0.09853229672347894874, 0.1972734588926643162, False, 0, Nothing, 0)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03380776867333094154, 0.03212992486625931843, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02414840619523638682, 0.06425984973251863686, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01931872495618910945, 0.02141994991083955024, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01931872495618910945, 0.03212992486625931843, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02414840619523638682, 0.04283989982167910049, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02414840619523638682, 0.05354987477709886173, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03380776867333094154, 0.04283989982167910049, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05795617486856732836, 0.1070997495541977235, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06761553734666188309, 0.1499396493758768378, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1159123497371346567, 0.3320092236180129941, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02897808743428366418, 0.06425984973251863686, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06278585610761459879, 0.1178097245096175055, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06761553734666188309, 0.1392296744204570558, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.053126493629520051, 0.07496982468793841892, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01931872495618910945, 0.03212992486625931843, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03380776867333094154, 0.01070997495541977512, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.08210458106380370824, 0, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07244521858570915351, -0.04283989982167910049, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0, -0.02930534313069443897, 0.1370960635635611879, 0.08906664904384342663

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.03074456033317574111, 0.09157923875113738177, 0.04713066849585878515, 0.6156161070251295886, 0.7879242212355905828, -0.01386471642380619762, 0.0006264757140860832685, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.03074456033317574111, 0.09157923875113738177, 0.04713066849585878515, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Part1-2@PROTO ASSEMBLY FINAL", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
ReDim TransformData(0 To 15) As Double
TransformData(0) = -0.6741149455165829085
TransformData(1) = -0.7380463761610777107
TransformData(2) = -0.02926750530324230895
TransformData(3) = 0.1256197925366891455
TransformData(4) = -0.07551117249908415041
TransformData(5) = -0.9892005512285426683
TransformData(6) = 0.7278658584891953831
TransformData(7) = -0.6705114536406626691
TransformData(8) = 0.1436164425909232378
TransformData(9) = 0.06046704145187926233
TransformData(10) = 0.07531234014911923624
TransformData(11) = 0.05254713697597492711
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
TransformDataVariant = TransformData
Set swMathUtil = swApp.GetMathUtility()
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
boolstatus = Part.Extension.SelectByRay(-0.05158711448262920385, 0.1593625522362458469, 0.1015857437709026811, 0.6156161070251295886, 0.7879242212355905828, -0.01386471642380619762, 0.002029781313638910015, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", -0.05158711448262920385, 0.1593625522362458469, 0.1015857437709026811, False, 0, Nothing, 0)
Part.ClearSelection2 True
Part.EditUndo2 1
Part.EditUndo2 1
boolstatus = Part.Extension.SelectByRay(-0.04924271485273205157, 0.1580555364081736025, 0.1042530759722235384, 0.6156161070251295886, 0.7879242212355905828, -0.01386471642380619762, 0.001118653077572675765, 3, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "VERTEX", -0.04924271485273205157, 0.1580555364081736025, 0.1042530759722235384, False, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, -0.03212992486625931843, 0.01403700333906954256, 0.142842255582195321, 0.1585849128496352733
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02414840619523638682, -0.3320092236180129941, 0.01403700333906954256, 0.142842255582195321, 0.1585849128496352733
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.009659362478094554727, -0.3641391484842723125, 0.01403700333906954256, 0.142842255582195321, 0.1585849128496352733
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.009659362478094554727, -0.1178097245096175055, 0.01403700333906954256, 0.142842255582195321, 0.1585849128496352733
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01448904371714183209, -0.1285196994650372737, 0.01403700333906954256, 0.142842255582195321, 0.1585849128496352733
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02897808743428366418, -0.1499396493758768378, 0.01403700333906954256, 0.142842255582195321, 0.1585849128496352733
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01448904371714183209, -0.08567979964335820098, 0.01403700333906954256, 0.142842255582195321, 0.1585849128496352733

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.0487408968877293472, 0.2940567607883549095, 0.1353771672175253515, 0.4605952774077100575, 0.07277379892447842502, -0.8846219331555229548, 0.001097963110326883674, 3, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "VERTEX", 0.0487408968877293472, 0.2940567607883549095, 0.1353771672175253515, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.0511764600732362851, 0.09081843365850517102, 0.1968238247212070746, 0.4605952774077100575, 0.07277379892447842502, -0.8846219331555229548, 0.00134168148703158103, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("Unknown", "POINTREF", 0.05062431696952501142, 0.09168782419657676985, 0.1966456625898197197, False, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01448904371714183209, -0.07496982468793841892, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03863744991237821891, -0.1178097245096175055, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.09176394354189826297, -0.08567979964335820098, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02414840619523638682, -0.02141994991083955024, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01448904371714183209, 0.04283989982167910049, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.009659362478094554727, 0.1070997495541977235, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.3534291735288525027, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04829681239047277364, 0.2677493738854943572, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.1497201184104655913, 0.1499396493758768378, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06278585610761459879, -0.09638977459877795528, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02897808743428366418, -0.2891693237963339214, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06278585610761459879, -0.2677493738854943572, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07244521858570915351, -0.1070997495541977235, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06278585610761459879, -0.02141994991083955024, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03380776867333094154, 0.03212992486625931843, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.009659362478094554727, 0.06425984973251863686, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06425984973251863686, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, 0.02141994991083955024, 0.07878675962109582542, 0.2089305704747346226, 0.1327415380732759331

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.05692638708625481075, 0.2982003216477768781, 0.1365552685455266868, 0.5974348381216113557, 0.008833569424625030767, -0.8018688061334124928, 0.001045082121352609297, 3, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "VERTEX", 0.05692638708625481075, 0.2982003216477768781, 0.1365552685455266868, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.06267244145851691428, 0.2773251981028526103, 0.138827585434626144, 0.5974348381216113557, 0.008833569424625030767, -0.8018688061334124928, 0.001045082121352609297, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.06267244145851691428, 0.2773251981028526103, 0.138827585434626144, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.06253182224673992096, 0.248139120638311006, 0.1392833444667758158, 0.5974348381216113557, 0.008833569424625030767, -0.8018688061334124928, 0.001045082121352609297, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.06253182224673992096, 0.248139120638311006, 0.1392833444667758158, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
boolstatus = Part.Extension.SelectByRay(0.06202648550578260256, 0.2991021409839946799, 0.1357616486706660908, 0.5974348381216113557, 0.008833569424625030767, -0.8018688061334124928, 0.001045082121352609297, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.06202648550578260256, 0.2991021409839946799, 0.1357616486706660908, False, 0, Nothing, 0)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01448904371714183209, 0, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, -0.3641391484842723125, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1014233060199928177, -0.3855590983951118211, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03380776867333094154, -0.02141994991083955024, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03380776867333094154, 0.05354987477709886173, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.009659362478094554727, 0.07496982468793841892, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0.1285196994650372737, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.08693426230285099254, 0.2998792987517536757, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06278585610761459879, 0.1392296744204570558, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03380776867333094154, 0.1070997495541977235, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06761553734666188309, 0.2677493738854943572, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.07727489982475643782, 0.3534291735288525027, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01931872495618910945, 0.06425984973251863686, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, 0.01070997495541977512, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.1820695742421361563, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.053126493629520051, -0.2677493738854943572, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03380776867333094154, -0.09638977459877795528, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04346713115142549627, -0.07496982468793841892, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04346713115142549627, -0.04283989982167910049, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03380776867333094154, -0.03212992486625931843, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.009659362478094554727, 0.04283989982167910049, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, 0.06425984973251863686, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02897808743428366418, 0.09638977459877795528, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.09176394354189826297, 0.396269073350531631, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.1642091621276074165, 0.5783386475926678427, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04346713115142549627, 0.1820695742421361563, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.09638977459877795528, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07727489982475643782, 0.07496982468793841892, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1110826684980873724, -0.06425984973251863686, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1352310746933237662, -0.4176890232613711396, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07244521858570915351, -0.3855590983951118211, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.2034895241529756926, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.09638977459877795528, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04283989982167910049, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04283989982167910049, 0.05894166766324815399, 0.08789240413444154854, 0.1643795066005395711

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.04605600955039790279, 0.1068486551086209602, 0.09799750200375001441, 0.6602094122061383796, 0.2778288781244204197, -0.6978070267019036432, 0.001285576085026418928, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.04605600955039790279, 0.1068486551086209602, 0.09799750200375001441, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.04924196197386260243, 0.1133070480798547275, 0.1010376509805992751, 0.6602094122061383796, 0.2778288781244204197, -0.6978070267019036432, 0.001285576085026418928, 3, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "VERTEX", 0.04924196197386260243, 0.1133070480798547275, 0.1010376509805992751, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.05114399039761551025, 0.09505853046910139881, 0.1978810576662933529, 0.6602094122061383796, 0.2778288781244204197, -0.6978070267019036432, 0.001285576085026418928, 3, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "VERTEX", 0.05114399039761551025, 0.09505853046910139881, 0.1978810576662933529, False, 0, Nothing, 0)
Part.ClearSelection2 True
Part.EditUndo2 1
Part.EditUndo2 1
Part.EditUndo2 1
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06278585610761459879, -0.2141994991083954469, 0.07528995675039595881, 0.272641550341063521, 0.1382078024498127888
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.4283989982167908939, 0.07528995675039595881, 0.272641550341063521, 0.1382078024498127888

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.06355149574881124863, 0.2925036026895213581, 0.1326838354548272036, 0.7031204400899350171, 0.4430669176498917006, -0.5561594674299451535, 0.001285576085026418928, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.06355149574881124863, 0.2925036026895213581, 0.1326838354548272036, False, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03863744991237821891, -0.224909474063815229, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04829681239047277364, -0.4069790483059513853, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.1285196994650372737, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004829681239047277364, -0.05354987477709886173, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07244521858570915351, -0.09638977459877795528, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.09659362478094554727, -0.07496982468793841892, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03380776867333094154, 0.09638977459877795528, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04346713115142549627, 0.2570393989300745474, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01448904371714183209, 0.1499396493758768378, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05795617486856732836, 0.1070997495541977235, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02897808743428366418, 0, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, -0.02141994991083955024, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.009659362478094554727, -0.01070997495541977512, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004829681239047277364, -0.01070997495541977512, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01931872495618910945, -0.01070997495541977512, 0.02186042701915732328, 0.1465878658990363015, 0.1731784091000935222

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.06751624891238423853, 0.2645447477264911695, 0.1394025087303265298, 0.666063532559537208, 0.05955683463899730246, -0.7435135197439879384, 0.001285576085026418928, 3, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "VERTEX", 0.06751624891238423853, 0.2645447477264911695, 0.1394025087303265298, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.06696789158559113275, 0.2252195562409085028, 0.1389152248501659415, 0.666063532559537208, 0.05955683463899730246, -0.7435135197439879384, 0.0008445775136182565425, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.06696789158559113275, 0.2252195562409085028, 0.1389152248501659415, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.06881176256962362459, 0.1859936297176929543, 0.1378211777275737404, 0.666063532559537208, 0.05955683463899730246, -0.7435135197439879384, 0.0008445775136182565425, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByRay(0.06557462421231212424, 0.2036619614645893972, 0.1384254312997150183, 0.666063532559537208, 0.05955683463899730246, -0.7435135197439879384, 0.0008445775136182565425, 3, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "VERTEX", 0.06557462421231212424, 0.2036619614645893972, 0.1384254312997150183, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.02317750603378954111, 0.2627428377235716539, 0.1424083795986348377, 0.666063532559537208, 0.05955683463899730246, -0.7435135197439879384, 0.0008445775136182565425, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.02317750603378954111, 0.2627428377235716539, 0.1424083795986348377, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.0445309843905171629, 0.2569903829388073269, 0.1419667455857060723, 0.666063532559537208, 0.05955683463899730246, -0.7435135197439879384, 0.0008445775136182565425, 3, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "VERTEX", 0.0445309843905171629, 0.2569903829388073269, 0.1419667455857060723, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.03682629897577723022, 0.2888013266922854205, 0.1361401585825242344, 0.666063532559537208, 0.05955683463899730246, -0.7435135197439879384, 0.00273643114412315102, 3, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "VERTEX", 0.03682629897577723022, 0.2888013266922854205, 0.1361401585825242344, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.04700901959591874402, 0.09497511970692329442, 0.1974621224810562126, 0.666063532559537208, 0.05955683463899730246, -0.7435135197439879384, 0.00273643114412315102, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.04700901959591874402, 0.09497511970692329442, 0.1974621224810562126, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.02823914624314038946, 0.1540818439139262919, 0.2037755620900359443, 0.666063532559537208, 0.05955683463899730246, -0.7435135197439879384, 0.0008600425671006204677, 3, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "VERTEX", 0.02823914624314038946, 0.1540818439139262919, 0.2037755620900359443, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.05972934925870276857, 0.160078288349950526, 0.1997281009447533506, 0.666063532559537208, 0.05955683463899730246, -0.7435135197439879384, 0.0008600425671006204677, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.05972934925870276857, 0.160078288349950526, 0.1997281009447533506, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(0.04602168748209578553, 0.1149718659569032297, 0.168445342009590604, 0.666063532559537208, 0.05955683463899730246, -0.7435135197439879384, 0.001486153555949871682, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.04602168748209578553, 0.1149718659569032297, 0.168445342009590604, False, 0, Nothing, 0)
Part.ClearSelection2 True

' Close Document
swAssembly = Nothing
Set Part = Nothing
swApp.CloseDoc "PROTO ASSEMBLY FINAL"

' New Document
Dim swSheetWidth As Double
swSheetWidth = 0
Dim swSheetHeight As Double
swSheetHeight = 0
Set Part = swApp.NewDocument("C:\ProgramData\SolidWorks\SOLIDWORKS 2023\templates\Part.prtdot", 0, swSheetWidth, swSheetHeight)
Dim swPart As PartDoc
Set swPart = Part
swApp.ActivateDoc2 "Part1", False, longstatus
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Part.SketchManager.InsertSketch True
Part.ClearSelection2 True
Dim skSegment As Object
Set skSegment = Part.SketchManager.CreateLine(0.000000, 0.000000, 0.000000, 0.140611, 0.000000, 0.000000)
Part.SetPickMode
Part.ClearSelection2 True
Set skSegment = Part.SketchManager.CreateLine(0.000000, 0.000000, 0.000000, -0.033242, 0.028275, 0.000000)
Part.SetPickMode
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Line2", "SKETCHSEGMENT", -0.01757637825064001236, 0.01413752163638437587, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0.04623351670277048298, -0.001528380717446958803, 0, True, 0, Nothing, 0)
Dim myDisplayDim As Object
Set myDisplayDim = Part.AddDimension2(0.0259824721965982719, 0.01643009271255481407, 0)
Part.ClearSelection2 True
Dim myDimension As Object
Set myDimension = Part.Parameter("D1@Sketch1")
myDimension.SystemValue = 2.617993877992
Part.SetPickMode
Part.ClearSelection2 True
Part.SetPickMode
Set skSegment = Part.SketchManager.CreateLine(0.000000, 0.000000, 0.000000, -0.109661, 0.000000, 0.000000)
Part.SetPickMode
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0.01719428307127829347, 0.0007641903587234794015, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line3", "SKETCHSEGMENT", -0.0294213288108539639, -0.001146285538085212163, 0, True, 0, Nothing, 0)
Part.SketchAddConstraints "sgCOLINEAR"
Part.SetPickMode
Part.ClearSelection2 True
Part.SetPickMode
boolstatus = Part.Extension.SelectByID2("Line2", "SKETCHSEGMENT", -0.01998487721438116371, 0.0111528816218329288, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line3", "SKETCHSEGMENT", -0.02391746422817195294, 1.055174942566489138e-05, 0, True, 0, Nothing, 0)
boolstatus = Part.DeSelectByID("Line3", "SKETCHSEGMENT", -0.02391746422817195294, 0, 0)
boolstatus = Part.DeSelectByID("Line2", "SKETCHSEGMENT", -0.01981799731573989642, 0.01144192608504155002, 0)
boolstatus = Part.Extension.SelectByID2("Line2", "SKETCHSEGMENT", -0.01998487721438116371, 0.0111528816218329288, 0, False, 0, Nothing, 0)
boolstatus = Part.DeSelectByID("Line2", "SKETCHSEGMENT", -0.01981799731573989642, 0.01144192608504155002, 0)
Part.SetPickMode
boolstatus = Part.Extension.SelectByID2("D1@Sketch1@Part1.SLDPRT", "DIMENSION", 0.02676921283846497857, 0.01639633097355398805, 0, False, 0, Nothing, 0)
Part.EditDelete
boolstatus = Part.Extension.SelectByID2("Line2", "SKETCHSEGMENT", -0.02632071184771078709, 0.01486699157930201215, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line3", "SKETCHSEGMENT", -0.02173269366495483856, -0.0004264023632177538214, 0, True, 0, Nothing, 0)
Set myDisplayDim = Part.AddDimension2(-0.03003482180517985656, 0.004817046988503312366, 0)
Part.ClearSelection2 True
Set myDimension = Part.Parameter("D1@Sketch1")
myDimension.SystemValue = 1.221730476396
Part.SetPickMode
Part.ClearSelection2 True
Part.SetPickMode
boolstatus = Part.Extension.SelectByID2("Line2", "SKETCHSEGMENT", -0.006220822666113373645, 0.01989196387470136551, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0.02851702928903868117, 0.000665982918390803369, 0, True, 0, Nothing, 0)
boolstatus = Part.DeSelectByID("Line1", "SKETCHSEGMENT", 0.02851702928903868464, 0, 0)
boolstatus = Part.DeSelectByID("Line2", "SKETCHSEGMENT", -0.007120851971049410242, 0.01956437999773735434, 0)
boolstatus = Part.Extension.SelectByID2("Line2", "SKETCHSEGMENT", -0.006220822666113373645, 0.01989196387470136551, 0, False, 0, Nothing, 0)
boolstatus = Part.DeSelectByID("Line2", "SKETCHSEGMENT", -0.007120851971049410242, 0.01956437999773735434, 0)
Part.SetPickMode
Part.SetPickMode
' MSGBOX
' Save changes to Part1?

Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
